const express = require('express');  
const router = express.Router();  
const customerController = require('../controllers/customerController');  
const auth = require('../middleware/auth');  
router.get('/', auth, customerController.getAllCustomers);  
router.post('/', auth, customerController.createCustomer);  
router.put('/:id', auth, customerController.updateCustomer);  
router.put('/:id/blacklist', auth, customerController.toggleBlacklist);
router.delete('/:id', auth, customerController.deleteCustomer);  
router.get('/:id/rentals', auth, customerController.getCustomerRentals);  
module.exports = router;  
