const express = require('express');  
const router = express.Router();  
const itemController = require('../controllers/itemController');  
const auth = require('../middleware/auth');  
router.get('/', auth, itemController.getAllItems);  
router.get('/:id', auth, itemController.getItemDetails);  
router.get('/ref/:ref', auth, itemController.getItemByReference);  
router.post('/', auth, itemController.createItem);  
router.put('/:id/status', auth, itemController.updateItemStatus);  
router.put('/:id', auth, itemController.updateItem);  
router.delete('/:id', auth, itemController.deleteItem);  
module.exports = router;  
